### PR TITLE
Pass custom user-specific Configuration to BalancedDistcp and Coercer

### PR DESCRIPTION
**Pull request by ashwanthkumar**
@sriram-r Please review

### CODE REVIEW

**Comment by ashwanthkumar** [comment]
## Usage 
```java
Pail source = Pail.create(source);
Pail target = Pail.create(target);
CopyArgs args = new CopyArgs();
args.conf = customConf;
target.absorb(source, args);
```

**Comment by sriram-r** [comment]
Do the tests pass with the distcp and coerce overloads removed?

**Comment by sriram-r** [comment]
If so, this, LGTM. Thanks.

**Comment by ashwanthkumar** [comment]
Yes, all tests pass locally.

**Comment by sriram-r** [comment]
Verified locally. All pass. Thanks.

**Comment by ashwanthkumar** [comment]
BTW, running `$ sbt test` doesn't run JUnit tests :( I'll send it in a patch for that soon.

**Pull request merged**
